### ISSUE TITLE
Are the multiple `go.mod` files necessary?

### ISSUE THREAD

**Issue by dprotaso** [knative/client-contrib#37]
Noticed this during https://github.com/knative/client-contrib/pull/36

I don't know what the trade offs are so I'm asking.

**Comment by rhuss** [comment]
We decided to make every plugin being self contained without a parent dependency. This has many benefits (different maintainers, different versions of dependencies) and we think that reflects the general nature of plugins. The alternative would be to have separate repositories.

The chosen approach has also drawbacks, i.e duplication. There we are planning to go away from vendoring to avoid explosion of subdued dependencies (which is even worse had every source plugin for a source from eventing-contrib has to import the whole eventing-contrib repo)

That's the reason why every plugin has its own go.mod

**Comment by dprotaso** [comment]
sounds good thanks
