### ISSUE TITLE
As knative admin, I want to remove registry credentials

### ISSUE THREAD

**Issue by 12345lcr** [knative/client-contrib#39]
Now we have `kn admin registry add` to add registry with credentials to enable Service deployment from it. But we are missing to remove the registry. The removal params require registry username and registry server url to remove the registry.

```
For example:
# To remove a registry
kn admin registry remove --username=myusername  --server=docker.io

Usage:
  kn admin registry remove [flags]

Flags:
  -h, --help              help for remove
      --server string     Registry Address
      --username string   Registry Username

Global Flags:
      --config string   config file (default is $HOME/.config/kn/plugins/admin.yaml)
```

**Comment by 12345lcr** [comment]
/assign
I would work on this new command.

**Comment by zhanggbj** [comment]
@12345lcr 
could you please help to close it as PR is merged? Thanks!
