### ISSUE TITLE
[discussion] how to setup clueters for e2e testing properly

### ISSUE THREAD

**Issue by lanceliuu** [knative/client-contrib#48]
Currently we have e2e test entrypoint in `test/e2e-tests.sh`, and it will iterate over all plugin directories to find and execute e2e test scripts. Based on such settings I have the following questions:
1. Do we have necessary permissions to create clusters in GKE as the same of knative/client?
1. Does every plugin need to set up clusters for its own and do teardown afterwards or to share the same cluster instead?

**Comment by daisy-ycguo** [comment]
> Currently we have e2e test entrypoint in `test/e2e-tests.sh`, and it will iterate over all plugin directories to find and execute e2e test scripts. Based on such settings I have the following questions:
> 
> 1. Do we have necessary permissions to create clusters in GKE as the same of knative/client?

Yes, but we don't need to bother. The e2e test framework will do that for us.

> 2. Does every plugin need to set up clusters for its own and do teardown afterwards or to share the same cluster instead?

Knative install and client install are handled by the test infrastructure. Every plugin need to set up the necessary resources for that plugin specific test. For example, the source-kafka plugin has to set up kafka cluster for its e2e test. Refer to the [e2e-tests.sh](https://github.com/daisy-ycguo/client-contrib/blob/kafka1/plugins/source-kafka/test/e2e-tests.sh#L47) in kafka plugin.

**Comment by lanceliuu** [comment]
Cool. Thanks for the clairification. @daisy-ycguo
