### ISSUE TITLE
Create repository knative-sandbox/kn-plugin-admin

### ISSUE THREAD

**Issue by rhuss** [knative/client-contrib#73]
As part of the migration of moving https://github.com/knative/client-contrib to the knative-sandbox organisation, we want to start with extracting/moving the `kn-admin` plugin first.

As suggested in https://github.com/knative/community/issues/174 we propose the name `kn-plugin-admin`

We would need:

* A GitHub repository `knative-sandbox/kn-plugin-admin`
* An OWNERS file with the content from https://github.com/knative/client-contrib/blob/master/OWNERS and https://github.com/knative/client-contrib/blob/master/plugins/admin/OWNERS combined
* A CI setup similar to that of `knative/client-contrib`

Next, we would need the following additional repositories (but maybe let's start with this canary first):

* kn-plugin-source-kafka
* kn-plugin-source-github
* kn-plugin-curl
* kn-plugin-migration
* kn-plugin-log
* kn-plugin-sample
* kn-plugin-shared

**Comment by rhuss** [comment]
Added to the TOC Backlog as suggested by https://github.com/knative/community/issues/153#issuecomment-661048746

**Comment by rhuss** [comment]
I wonder whether I should open issues for the other 7 repos to create, too, or a catch-all ticket?

**Comment by evankanderson** [comment]
I think one ticket for creating all of these is fine.

**Comment by rhuss** [comment]
@evankanderson thanks for picking this up ! However there is still a discussion open about the proper prefix (`kn-plugin-` vs. only `kn-` in https://github.com/knative/community/issues/174), so we should probably wait until this decision has been taken (should be soon)

/hold

**Comment by zhanggbj** [comment]
@evankanderson @rhuss 
Please let me know if the repo is ready. Then I could consolidate and raise a PR for kn-admin to the new repo:-)

**Comment by evankanderson** [comment]
Let me know what prefix you want and I can get them done in a few days.

**Comment by rhuss** [comment]
@evankanderson we decided to go for a `kn-plugin` prefixes for plugins, so `kn-plugin-admin` would be the repo that we would like to have.

**Comment by rhuss** [comment]
I'm closing this in favor of #75 which uses the new template for creating repos.
