### ISSUE TITLE
New Repo: knative-sandbox/kn-plugin-admin

### ISSUE THREAD

**Issue by rhuss** [knative/client-contrib#75]
## Repo information

Org: knative-sandbox

Repo: kn-plugin-admin

Purpose (Description): This repo holds the `kn admin` plugin which can be used to configure Kubernetes based Knative installations. Currently it is contained in a subdirectory of this `client-contrib` repo but we decided to move out all plugins into individual repostitories.

This issue replaces #73 

Sponsoring WG: client

## Actions to fulfill

This area is used for the TOC to track the [repo creation
process](/mechanics/CREATING-A-SANDBOX-REPO.md)

- [x] Add this issue to the [TOC project board](https://github.com/orgs/knative/projects/9) for review.

- [x] Send a PR adding entries for this repo in `/peribolos/knative-sandbox.yaml`
  - [x] Add the repository and a description.
  - [x] Grant `Knative Admin` the `admin` privilege.
  - [x] Grant the sponsoring WG the `write` privilege.
  - PR: https://github.com/knative/community/pull/264

_Once the TOC has approved the above, it will merge and Peribolos will create an empty repository._

- [x] (golang) Send a PR to add aliases for `knative.dev/$REPONAME` import paths ([sample](https://github.com/knative/website/pull/187)).

- [x] Have a lead from the sponsoring WG bootstrap the Git repository by pushing an
  appropriate "template" repository ([basic](https://github.com/knative-sandbox/wg-repository),
  [sample-controller](https://github.com/knative-sandbox/sample-controller),
  [sample-source](https://github.com/knative-sandbox/sample-source)) to the new repository as
  a git remote.  For example:

  ```shell
    git clone https://github.com/knative-sandbox/sample-controller.git
    cd sample-controller
    git remote add newrepo https://github.com/knative-sandbox/$REPONAME.git
    git push newrepo master
  ```

- [x] Set up [test-infra](https://github.com/knative/test-infra) following the
  docs linked at the beginning.

- [x] Create a sample PR to verify Prow (e.g. edit the boilerplate README)

_Once Prow has been verified._

- [x] Have a member of the TOC enable branch protections so that `tide` is a required presubmit check.

**Comment by mattmoor** [comment]
@evankanderson was it still your intention to do this (it is assigned to you still) given the new self-serve process?

@rhuss the new process should require minimal TOC action if you want to run through it to unblock.

**Comment by rhuss** [comment]
@mattmoor From the template it is not really clear to me what action items I can complete myself. Also it says

> This area is used for the TOC to track the [repo creation process](/mechanics/CREATING-A-SANDBOX-REPO.md)

so I assumed that section is for the TOC only (btw, the link is not working but could be also because I copied over the template directly from @evankanderson not-yet-merged PR). Update: I just checked the merged version but the link still looks a bit bogus: https://github.com/mattmoor/community/blob/467457498c99f8b08c0739d8693abe88a8b11730/mechanics/CREATING-A-SANDBOX-REPO.md Shouldn't this point to a repo in the kantive orga ?

> * Send a PR adding entries for this repo in `/peribolos/knative-sandbox.yaml`

In which repo ?

> Once the TOC has approved the above, it will merge and Peribolos will create an empty repository.

So it this really something I can do myself ?

The remaining parts are something I can do myself, but for this I would neet to have the repository created first, which is not yet the case.

-----------

Finally my question is where these kind of issues should be created ? in the `knative/community` or in the original repo that should be moved and this issue should be added to the TOC's project board ? There has been some discussion around this lately (cc @n3wscott )

**Comment by rhuss** [comment]
Ok, I think to understand now, so the actions are to be performed by the requestor, the checkmarks are to be filles by the requestor, too and TOC just acts on the gate steps (approving PRs and enabling branch protection).

I added some extra explanation with https://github.com/knative/community/pull/263 (which might be helpful to avoid confusion for other users, too)

**Comment by mattmoor** [comment]
> This area is used for the TOC to track

Yeah we should tweak this to just say "used to track".

> In which repo ?

knative/community.  This should be a link.

> So it this really something I can do myself

All you need from TOC is `/approve` on the PR to manipulate the org ACLs, so it's about as close to self-service as we can get, I think.  Once the repo is created, as a WG lead you'll have write access to the new repo.

> I added some extra explanation with

Cool, I added my comments above on your PR.  thanks for the updates!

**Comment by evankanderson** [comment]
https://github.com/knative/website/pull/208 for the next steps

**Comment by evankanderson** [comment]
Just needs a `/lgtm` on https://github.com/knative/website/pull/208 to move to the next step.

**Comment by mattmoor** [comment]
@evankanderson I stamped it.

**Comment by evankanderson** [comment]
(Added Prow testing)

**Comment by mattmoor** [comment]
@evankanderson to follow up

**Comment by evankanderson** [comment]
Prow seems to be working, though it's not clear if tests are being run. @rhuss , are you expecting tests to run? It looks like only e2e tests are present.

**Comment by mattmoor** [comment]
Ping @rhuss

**Comment by rhuss** [comment]
Sorry for the delayed answer. Let me check ....

**Comment by navidshaikh** [comment]
here is the latest PR with prow configs for the plugin https://github.com/knative/test-infra/pull/2594 PTAL

**Comment by evankanderson** [comment]
Looks like this has been complete for a while.

/close
